trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  policy: "Default IaC policy,mb-misconfig,mb-secrets,Default secrets policy,Default vulnerabilities policy"
  SCAN_PATH: "$(Build.Repository.LocalPath)"
  IMAGE: setestimage
  TAG: $(Build.BuildNumber)

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo "##[command]Obtaining WizCLI from the inter-webs..."
      sudo curl -o /usr/bin/wizcli https://wizcli.app.wiz.io/wizcli
      echo "##[command]Making WizCLI executable"
      sudo chmod +x /usr/bin/wizcli
      /usr/bin/./wizcli auth --id $(WIZ_CLIENT_ID) --secret $(WIZ_CLIENT_SECRET)
  displayName: Download latest WizCLI and Authenticate

- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/./wizcli iac scan --path "$SCAN_PATH" -p "$policy"
  displayName: Scan IaC with WizCLI
  condition: succeededOrFailed()

- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/./wizcli docker scan --image "$IMAGE:$TAG" -p "secrets"
  displayName: Scan Image with WizCLI
  condition: succeededOrFailed()
  
- task: CmdLine@2
  inputs:
    script: |
      docker build "$SCAN_PATH" -t "$IMAGE:$TAG"
  displayName: Build Docker Image
  condition: succeededOrFailed()


- task: CmdLine@2
  inputs:
    script: |
      /usr/bin/./wizcli docker scan --image "$IMAGE:$TAG" -p "secrets"
  displayName: Scan Image with WizCLI
  condition: succeededOrFailed()


